#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your 
# load-balancer IP (lb-01)

if [ "$#" -gt 2 ]; then
    exit 1
fi

for sub in www lb-01 web-01 web-02
do 
    if [ -n "$2" ] && [ "$2" != $sub ]; then
        continue
    fi
    tmpfile=$(mktemp /tmp/dig_www.XXXXXX)
    dig "$sub.$1" > "$tmpfile"
    ip_address=$(grep -A1 'ANSWER SECTION:' "$tmpfile" | awk -F' ' '{ print $5 }' | awk "NR==2")
    record=$(grep -A1 'ANSWER SECTION:' "$tmpfile" | awk -F' ' '{ print $4 }' | awk "NR==2")
    printf "The subdomain %s is a %s record and points to %s\n" "$sub" "$record" "$ip_address"
    rm "$tmpfile"
done