#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)
# curl http://54.160.94.77/   --> returns string "Hello World!"
# curl http://54.160.94.77/   --> returns header info

sudo apt-get update && sudo apt-get -y install nginx
printf "server {
\tlisten 80 default_server;
\tlisten [::]:80 default_server;
\troot /var/www/html;
\tindex index.html index.htm index.nginx-debian.html;
\tlocation / {
\t\treturn 200 \"%s\"
\t}
}\n" "Hello World\n" | sudo tee /etc/nginx/sites-available/default
sudo service nginx stop && sudo service nginx start
