#!/usr/bin/env bash
# Install nginx on your web-01
apt-get update && apt-get install -y nginx
echo '<html><head></head><body>Hello World!</body></html>' > /usr/share/nginx/html/index.html
service nginx reload
