#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”

sudo apt-get update && sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/
printf "server {
     listen 80 default_server;
     listen [::]:80 default_server;
     server_name _;
     location /redirect_me {
          return 301 http://www.staggeringbeauty.com/;
     }
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
