#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”

sudo apt-get update && sudo apt-get -y install nginx
printf "server {
     listen 80 default_server;
     listen [::]:80 default_server;
     rewrite ^/redirect_me http://www.staggeringbeauty.com/ permanent;
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx stop && sudo service nginx start