#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”
# have a custom 404 page that contains the string Ceci n'est pas une page.

sudo apt-get update && sudo apt-get -y install nginx
printf %s "server {
     listen 80 default_server;
     listen [::]:80 default_server;
     root /var/www/html;
     index index.html index.htm index.nginx-debian.html;
     location / {
          return 404 \"Ceci n'est pas une page\n\";
	}
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx stop && sudo service nginx start
