#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”
# have a custom 404 page that contains the string Ceci n'est pas une page.

sudo apt-get update && sudo apt-get -y install nginx
printf "%s\n" "Ceci n'est pas une page" | sudo tee /var/www/html/404.html 
printf "server {
     listen 80 default_server;
     listen [::]:80 default_server;
     rewrite ^/redirect_me http://www.staggeringbeauty.com/ permanent;
     error_page 404 /404.html;
     location = /404.html {
          root /var/www/html;
          internal;
     }
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx stop && sudo service nginx start
sudo service nginx reload