#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

sudo apt-get update && sudo apt-get -y install nginx && histchars=
printf "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    location / {
        return 200 \"%s\";
    }
    add_header X-Served-By $hostname
}\n" "Hello World!\n" | sudo tee /etc/nginx/sites-available/default

unset histchars && sudo service nginx stop && sudo service nginx start