#!/usr/bin/env bash
# Install and configure a load balancer

sudo apt-get update
sudo apt-get install haproxy -y

echo -e "\nfrontend Server\n\tbind *:80\n\tmode http\n\tdefault_backend nodes\n\nbackend nodes\n\tbalance roundrobin\n\tserver 61696-web-01 54.160.108.206:80 check\n\tserver 61696-web-02 52.91.160.107:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy stop && sudo service haproxy start