#!/usr/bin/env bash
# Install and configure a load balancer

sudo apt-get update -y
sudo apt-get install haproxy -y

printf "
frontend Server
    bind *:80
    mode http
    default_backend nodes
    
backend nodes
    balance roundrobin
    server 57022-web-01 100.25.45.223:80 check
    server 57022-web-02 52.91.116.127:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart