#!/usr/bin/env bash
# Ubuntu container's Nginx installation from listening on port 80.
sudo sed -i 's/listen 8080/listen 80/' /etc/nginx/sites-enabled/default
sudo service nginx restart && sudo ufw allow 'Nginx HTTP'
