#!/usr/bin/env bash
# The file /etc/passwd has already been covered in a previous project and you should be familiar with it.
# Today we will make up a story based on it.

while IFS=: read -r q w e r t y u
do
	echo "The user $q is part of the $r gang, lives in $y and rides $u. $e's place is protected by the passcode $w, more info about the user here: $t"
done < "/etc/passwd"