#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while
x=1; 
while [ $x -lt 10 ]; 
do 
    if [ "$x" = 8 ] 
    then 
        echo "Hi"; 
    else
        echo "Best School"
    fi; 
    ((x++)); 
done
