#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while
# while showing the bad luck number in different country

x=1; 
while [ $x -lt 21 ]; 
do 
    echo $x;
    case $x in
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
    esac
    ((x++)); 
done
