#!/usr/bin/env bash
# This script is displays the time for 12 hours and 59 minutes

hour=0
seconds=1;
while [ $hour -lt 13 ]
do
    echo "Hour: $hour"
    while [ $seconds -lt 60 ]
    do
        echo $seconds
        ((seconds++))
    done
    seconds=1;
    ((hour++))
done    
