#!/usr/bin/env bash
# this script displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)

IFS="-"
for file in *
do 
    read -a strarr <<< "$file"
    echo "${strarr[1]}"
done