#!/usr/bin/env bash
# fix a failed apache service
sed -i 's/#ServerName www.example.com/ServerName www.example.com/g' /etc/apache2/sites-available/000-default.conf
service apache2 stop
service apache2 start
service apache2 reload