#!/usr/bin/env bash
# Run Nginx as Nginx
chmod 644 /etc/nginx/nginx.conf
sed -i '1s/.*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2
su nginx --shell=/bin/bash --command='service nginx restart'
